[tool.poetry]
name = "vs-lab"
version = "0.1.0"
description = ""
authors = ["vitorhcsousa <vitorsousavhcs@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
